<?xml version="1.0" encoding="iso-8859-1"?>
<!--
<!DOCTYPE diccionario SYSTEM "/usr/local/jakarta-tomcat-3.2.3/webapps/Diaweb/WEB-INF/classes/idiomas/diccionario.dtd">
-->
<!DOCTYPE diccionario[
	<!ELEMENT diccionario (entrada)*>
	<!ELEMENT entrada (idioma)*>
	<!ATTLIST entrada numero CDATA #REQUIRED>
	<!ELEMENT idioma (texto,ayuda?)>
	<!ATTLIST idioma identificador CDATA #REQUIRED>
	<!ELEMENT texto (#PCDATA)>
	<!ELEMENT ayuda (#PCDATA)>
]>
<diccionario>
	<entrada numero="1">
		<idioma identificador="1">
			<texto>¿Desea guardar la simulación?</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Do you want to save simulation?</texto>
		</idioma>
	</entrada>
	<entrada numero="10">
		<idioma identificador="1">
			<texto>Representación de Algoritmos de Estructuras de Datos v1.0</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Representation of Algorithms of Data Structures v1.0</texto>
		</idioma>
	</entrada>
	<entrada numero="1001">
		<idioma identificador="1">
			<texto>Opciones</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Options</texto>
		</idioma>
	</entrada>
	<entrada numero="1002">
		<idioma identificador="1">
			<texto>Ayuda</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Help</texto>
		</idioma>
	</entrada>
	<entrada numero="1003">
		<idioma identificador="1">
			<texto>Acerca de ..</texto>
		</idioma>
		<idioma identificador="2">
			<texto>About ..</texto>
		</idioma>
	</entrada>
	<entrada numero="1004">
		<idioma identificador="1">
			<texto>Nuevo</texto>
		</idioma>
		<idioma identificador="2">
			<texto>New</texto>
		</idioma>
	</entrada>
	<entrada numero="1005">
		<idioma identificador="1">
			<texto>Abrir</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Open</texto>
		</idioma>
	</entrada>
	<entrada numero="1006">
		<idioma identificador="1">
			<texto>Guardar</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Save</texto>
		</idioma>
	</entrada>
	<entrada numero="1007">
		<idioma identificador="1">
			<texto>Salir</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Exit</texto>
		</idioma>
	</entrada>
	<entrada numero="1008">
		<idioma identificador="1">
			<texto>Imprimir dibujo</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Print drawing</texto>
		</idioma>
	</entrada>
	<entrada numero="101">
		<idioma identificador="1">
			<texto>Imprimir texto</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Print text</texto>
		</idioma>
	</entrada>
	<entrada numero="1010">
		<idioma identificador="1">
			<texto>Guardar ejecución</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Save simulation</texto>
		</idioma>
	</entrada>
	<entrada numero="1011">
		<idioma identificador="1">
			<texto>Mostrar ejecucion(texto)</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Show simulation(text)</texto>
		</idioma>
	</entrada>
	<entrada numero="1013">
		<idioma identificador="1">
			<texto>Ayuda</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Help</texto>
		</idioma>
	</entrada>
	<entrada numero="1014">
		<idioma identificador="1">
			<texto>Ayuda en-línea</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Online help</texto>
		</idioma>
	</entrada>
	<entrada numero="1015">
		<idioma identificador="1">
			<texto>TDA Pila</texto>
		</idioma>
		<idioma identificador="2">
			<texto>TDA Stack</texto>
		</idioma>
	</entrada>
	<entrada numero="1016">
		<idioma identificador="1">
			<texto>Apilar</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Push</texto>
		</idioma>
	</entrada>
	<entrada numero="1017">
		<idioma identificador="1">
			<texto>Desapilar</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Pop</texto>
		</idioma>
	</entrada>
	<entrada numero="1018">
		<idioma identificador="1">
			<texto>Cima</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Top</texto>
		</idioma>
	</entrada>
	<entrada numero="1019">
		<idioma identificador="1">
			<texto>Cima y desapilar</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Top and Pop</texto>
		</idioma>
	</entrada>
	<entrada numero="102">
		<idioma identificador="1">
			<texto>Es vacía</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Is empty</texto>
		</idioma>
	</entrada>
	<entrada numero="1020">
		<idioma identificador="1">
			<texto>Vaciar</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Make empty</texto>
		</idioma>
	</entrada>
	<entrada numero="1021">
		<idioma identificador="1">
			<texto>Información sobre TDA Pila</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Information about TDA Stack</texto>
		</idioma>
	</entrada>
	<entrada numero="1023">
		<idioma identificador="1">
			<texto>Insertar un elemento en la pila</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Insert a new item into the stack, if not already full</texto>
		</idioma>
	</entrada>
	<entrada numero="1024">
		<idioma identificador="1">
			<texto>Elimina el último elemento insertado</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Remove the most recently inserted item from the stack</texto>
		</idioma>
	</entrada>
	<entrada numero="1025">
		<idioma identificador="1">
			<texto>Devuelve el último elemento insertado</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Get the most recently inserted item in the stack</texto>
		</idioma>
	</entrada>
	<entrada numero="1026">
		<idioma identificador="1">
			<texto>Devuelve y elimina el último elemento</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Return and remove most recently inserted item from the stack</texto>
		</idioma>
	</entrada>
	<entrada numero="1027">
		<idioma identificador="1">
			<texto>Devuelve verdadero si vacía, falso si no vacía</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Test if the stack is logically empty</texto>
		</idioma>
	</entrada>
	<entrada numero="1028">
		<idioma identificador="1">
			<texto>Vacía la pila</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Make the stack logically empty</texto>
		</idioma>
	</entrada>
	<entrada numero="1029">
		<idioma identificador="1">
			<texto>Introduzca elemento que desea apilar (máx. 4 caracteres)</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Introduce element that it wants to push (máx. 4 characters)</texto>
		</idioma>
	</entrada>
	<entrada numero="103">
		<idioma identificador="1">
			<texto>Archivo</texto>
		</idioma>
		<idioma identificador="2">
			<texto>File</texto>
		</idioma>
	</entrada>
	<entrada numero="1030">
		<idioma identificador="1">
			<texto>Apilar un elemento</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Push an element</texto>
		</idioma>
	</entrada>
	<entrada numero="1031">
		<idioma identificador="1">
			<texto>Aviso: No ha introducido nada</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Warning: It has not introduced anything</texto>
		</idioma>
	</entrada>
	<entrada numero="1032">
		<idioma identificador="1">
			<texto>Información sobre TDA Pila</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Information about TDA Stack</texto>
		</idioma>
	</entrada>
	<entrada numero="1033">
		<idioma identificador="1">
			<texto>Apilado: </texto>
		</idioma>
		<idioma identificador="2">
			<texto>Pushed:  </texto>
		</idioma>
	</entrada>
	<entrada numero="1034">
		<idioma identificador="1">
			<texto>Imposible desapilar: Pila vacía</texto>
		</idioma>
		<idioma identificador="2">
			<texto>It's impossible to pop: Empty stack</texto>
		</idioma>
	</entrada>
	<entrada numero="1035">
		<idioma identificador="1">
			<texto>Desapilar un elemento</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Pop an element</texto>
		</idioma>
	</entrada>
	<entrada numero="1036">
		<idioma identificador="1">
			<texto>Desapilado: </texto>
		</idioma>
		<idioma identificador="2">
			<texto>Poped: </texto>
		</idioma>
	</entrada>
	<entrada numero="1037">
		<idioma identificador="1">
			<texto>Elemento Cima: </texto>
		</idioma>
		<idioma identificador="2">
			<texto>Top element: </texto>
		</idioma>
	</entrada>
	<entrada numero="1038">
		<idioma identificador="1">
			<texto>Imposible obtener cima: pila vacía</texto>
		</idioma>
		<idioma identificador="2">
			<texto>It's impossible to get top: empty stack</texto>
		</idioma>
	</entrada>
	<entrada numero="1039">
		<idioma identificador="1">
			<texto>Obtener el elemento cima</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Get top element</texto>
		</idioma>
	</entrada>
	<entrada numero="1040">
		<idioma identificador="1">
			<texto>Imposible obtener cima y desapilar: pila vacía </texto>
		</idioma>
		<idioma identificador="2">
			<texto>It's impossible to top and pop: empty stack </texto>
		</idioma>
	</entrada>
	<entrada numero="1041">
		<idioma identificador="1">
			<texto>Obtener cima y desapilar</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Top and pop</texto>
		</idioma>
	</entrada>
	<entrada numero="1042">
		<idioma identificador="1">
			<texto>Operación es vacía</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Method is empty</texto>
		</idioma>
	</entrada>
	<entrada numero="1043">
		<idioma identificador="1">
			<texto>La pila está vacía </texto>
		</idioma>
		<idioma identificador="2">
			<texto>Empty stack </texto>
		</idioma>
	</entrada>
	<entrada numero="1044">
		<idioma identificador="1">
			<texto>La pila no está vacía </texto>
		</idioma>
		<idioma identificador="2">
			<texto>Not empty stack </texto>
		</idioma>
	</entrada>
	<entrada numero="1045">
		<idioma identificador="1">
			<texto>Vaciar pila </texto>
		</idioma>
		<idioma identificador="2">
			<texto>Make empty stack </texto>
		</idioma>
	</entrada>
	<entrada numero="1046">
		<idioma identificador="1">
			<texto>Imposible vaciar pila: pila ya vacía </texto>
		</idioma>
		<idioma identificador="2">
			<texto>It's impossible to make empty stack: stack is empty </texto>
		</idioma>
	</entrada>
	<entrada numero="1047">
		<idioma identificador="1">
			<texto>Se ha vaciado la pila </texto>
		</idioma>
		<idioma identificador="2">
			<texto>Stack has been made empty </texto>
		</idioma>
	</entrada>
	<entrada numero="1048">
		<idioma identificador="1">
			<texto>Estructura de Datos estudiada en Algoritmia(1ºI.T.I.S.)</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Data Structure studied in Algorithms(1ºI.T.I.S.)</texto>
		</idioma>
	</entrada>
	<entrada numero="1049">
		<idioma identificador="1">
			<texto>Pregunta</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Question</texto>
		</idioma>
	</entrada>
	<entrada numero="1050">
		<idioma identificador="1">
			<texto>Si</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Yes</texto>
		</idioma>
	</entrada>
	<entrada numero="1051">
		<idioma identificador="1">
			<texto>Operaciones</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Methods</texto>
		</idioma>
	</entrada>
	<entrada numero="1052">
		<idioma identificador="1">
			<texto>Ejecución de algoritmos</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Execution of algorithms</texto>
		</idioma>
	</entrada>
	<entrada numero="1053">
		<idioma identificador="1">
			<texto>Representación gráfica</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Graphical representation</texto>
		</idioma>
	</entrada>
	<entrada numero="1054">
		<idioma identificador="1">
			<texto>TDA Cola</texto>
		</idioma>
		<idioma identificador="2">
			<texto>TDA Queue</texto>
		</idioma>
	</entrada>
	<entrada numero="1055">
		<idioma identificador="1">
			<texto>Información sobre el TDA Cola</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Information about TDA Queue</texto>
		</idioma>
	</entrada>
	<entrada numero="1056">
		<idioma identificador="1">
			<texto>Encolar</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Enqueue</texto>
		</idioma>
	</entrada>
	<entrada numero="1057">
		<idioma identificador="1">
			<texto>Inserta un elemento en la cola</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Insert a new item into the queue</texto>
		</idioma>
	</entrada>
	<entrada numero="1058">
		<idioma identificador="1">
			<texto>Frente</texto>
		</idioma>
		<idioma identificador="2">
			<texto>GetFront</texto>
		</idioma>
	</entrada>
	<entrada numero="1059">
		<idioma identificador="1">
			<texto>Devuelve el primer elemento de la cola</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Get the least recently inserted item in the queue</texto>
		</idioma>
	</entrada>
	<entrada numero="1060">
		<idioma identificador="1">
			<texto>Quitar frente</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Dequeue</texto>
		</idioma>
	</entrada>
	<entrada numero="1061">
		<idioma identificador="1">
			<texto>Devuelve y elimina el primer elemento</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Return and remove the least recently inserted item from the queue</texto>
		</idioma>
	</entrada>
	<entrada numero="1062">
		<idioma identificador="1">
			<texto>Es vacía</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Is empty</texto>
		</idioma>
	</entrada>
	<entrada numero="1063">
		<idioma identificador="1">
			<texto>Devuelve true si vacía,false si no vacía</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Test if the queue is logically empty</texto>
		</idioma>
	</entrada>
	<entrada numero="1064">
		<idioma identificador="1">
			<texto>Vaciar </texto>
		</idioma>
		<idioma identificador="2">
			<texto>Make empty </texto>
		</idioma>
	</entrada>
	<entrada numero="1065">
		<idioma identificador="1">
			<texto>Elimina todos los elementos,vacía la cola</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Make the queue logically empty</texto>
		</idioma>
	</entrada>
	<entrada numero="1066">
		<idioma identificador="1">
			<texto>Introduzca elemento a encolar (max. 4 caracteres)</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Enter an element to queue (max. 4 characters)</texto>
		</idioma>
	</entrada>
	<entrada numero="1067">
		<idioma identificador="1">
			<texto>Encolar un elemento</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Enqueue an element</texto>
		</idioma>
	</entrada>
	<entrada numero="1068">
		<idioma identificador="1">
			<texto>Encolado: </texto>
		</idioma>
		<idioma identificador="2">
			<texto>Enqueued: </texto>
		</idioma>
	</entrada>
	<entrada numero="1069">
		<idioma identificador="1">
			<texto>Elemento frente (Primero de la cola): </texto>
		</idioma>
		<idioma identificador="2">
			<texto>Front element (First of queue): </texto>
		</idioma>
	</entrada>
	<entrada numero="1070">
		<idioma identificador="1">
			<texto>Imposible obtener frente. Cola vacía</texto>
		</idioma>
		<idioma identificador="2">
			<texto>It's impossible to get front. Empty queue</texto>
		</idioma>
	</entrada>
	<entrada numero="1071">
		<idioma identificador="1">
			<texto>Devolver el elemento frente</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Get front of the queue</texto>
		</idioma>
	</entrada>
	<entrada numero="1072">
		<idioma identificador="1">
			<texto>Frente: </texto>
		</idioma>
		<idioma identificador="2">
			<texto>Front: </texto>
		</idioma>
	</entrada>
	<entrada numero="1073">
		<idioma identificador="1">
			<texto>Desencolar</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Dequeue</texto>
		</idioma>
	</entrada>
	<entrada numero="1074">
		<idioma identificador="1">
			<texto>Desencolado: </texto>
		</idioma>
		<idioma identificador="2">
			<texto>Dequeued: </texto>
		</idioma>
	</entrada>
	<entrada numero="1075">
		<idioma identificador="1">
			<texto>La cola está vacía</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Queue is empty</texto>
		</idioma>
	</entrada>
	<entrada numero="1076">
		<idioma identificador="1">
			<texto>La cola no está vacía</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Queue is not empty</texto>
		</idioma>
	</entrada>
	<entrada numero="1077">
		<idioma identificador="1">
			<texto>Vaciado de la cola</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Make queue empty</texto>
		</idioma>
	</entrada>
	<entrada numero="1078">
		<idioma identificador="1">
			<texto>La cola ha sido vaciada</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Queue has been made empty</texto>
		</idioma>
	</entrada>
	<entrada numero="1079">
		<idioma identificador="1">
			<texto>Imposible vaciar cola. Cola ya vacía</texto>
		</idioma>
		<idioma identificador="2">
			<texto>It's impossible to make empty queue. Queue is empty yet</texto>
		</idioma>
	</entrada>
	<entrada numero="1080">
		<idioma identificador="1">
			<texto>Simulación incorrecta</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Incorrect simulation</texto>
		</idioma>
	</entrada>
	<entrada numero="1081">
		<idioma identificador="1">
			<texto>Error: fichero.raed incorrecto</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Error: file.raed incorrect!</texto>
		</idioma>
	</entrada>
	<entrada numero="1082">
		<idioma identificador="1">
			<texto>Aviso: no existe árbol, debe crearlo</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Warning: it doesn't exist a tree, you must create it</texto>
		</idioma>
	</entrada>
	<entrada numero="1083">
		<idioma identificador="1">
			<texto>Información sobre TDA Árbol Binario</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Information about TDA Binary Tree</texto>
		</idioma>
	</entrada>
	<entrada numero="1084">
		<idioma identificador="1">
			<texto>Recorrido pre-orden del árbol binario</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Pre-order route for binary tree</texto>
		</idioma>
	</entrada>
	<entrada numero="1085">
		<idioma identificador="1">
			<texto>Recorrido en-orden del árbol binario</texto>
		</idioma>
		<idioma identificador="2">
			<texto>In-order route for binary tree</texto>
		</idioma>
	</entrada>
	<entrada numero="1086">
		<idioma identificador="1">
			<texto>Recorrido post-orden del árbol binario</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Post-order route for binary tree</texto>
		</idioma>
	</entrada>
	<entrada numero="1087">
		<idioma identificador="1">
			<texto>Recorrido por niveles del árbol binario</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Level-order route for binary tree</texto>
		</idioma>
	</entrada>
	<entrada numero="1088">
		<idioma identificador="1">
			<texto>Recorrido finalizado</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Finalized route</texto>
		</idioma>
	</entrada>
	<entrada numero="1089">
		<idioma identificador="1">
			<texto>TDA Árbol Binario</texto>
		</idioma>
		<idioma identificador="2">
			<texto>TDA Binary Tree</texto>
		</idioma>
	</entrada>
	<entrada numero="1090">
		<idioma identificador="1">
			<texto>Nuevo Árbol Binario</texto>
		</idioma>
		<idioma identificador="2">
			<texto>New Binary Tree</texto>
		</idioma>
	</entrada>
	<entrada numero="1091">
		<idioma identificador="1">
			<texto>Crea un nuevo árbol</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Create new tree</texto>
		</idioma>
	</entrada>
	<entrada numero="1092">
		<idioma identificador="1">
			<texto>Nuevo nodo</texto>
		</idioma>
		<idioma identificador="2">
			<texto>New node</texto>
		</idioma>
	</entrada>
	<entrada numero="1093">
		<idioma identificador="1">
			<texto>Creación de nodos hijos</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Create child nodes</texto>
		</idioma>
	</entrada>
	<entrada numero="1094">
		<idioma identificador="1">
			<texto>Recorrido</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Route</texto>
		</idioma>
	</entrada>
	<entrada numero="1095">
		<idioma identificador="1">
			<texto>Recorrido del árbol</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Tree route</texto>
		</idioma>
	</entrada>
	<entrada numero="1096">
		<idioma identificador="1">
			<texto>Es vacío</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Is empty</texto>
		</idioma>
	</entrada>
	<entrada numero="1097">
		<idioma identificador="1">
			<texto>Devuelve true si vacío, false si no vacío </texto>
		</idioma>
		<idioma identificador="2">
			<texto>Test if the tree is logically empty</texto>
		</idioma>
	</entrada>
	<entrada numero="1098">
		<idioma identificador="1">
			<texto>Vaciar</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Make empty</texto>
		</idioma>
	</entrada>
	<entrada numero="1099">
		<idioma identificador="1">
			<texto>Vaciar el árbol</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Make an empty tree</texto>
		</idioma>
	</entrada>
	<entrada numero="11">
		<idioma identificador="1">
			<texto>Altura</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Height</texto>
		</idioma>
	</entrada>
	<entrada numero="1100">
		<idioma identificador="1">
			<texto>Devuelve la altura</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Return tree height</texto>
		</idioma>
	</entrada>
	<entrada numero="1101">
		<idioma identificador="1">
			<texto>Tamaño</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Size</texto>
		</idioma>
	</entrada>
	<entrada numero="1102">
		<idioma identificador="1">
			<texto>Devuelve el tamaño</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Return size</texto>
		</idioma>
	</entrada>
	<entrada numero="1104">
		<idioma identificador="1">
			<texto>Siguiente paso</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Next step</texto>
		</idioma>
	</entrada>
	<entrada numero="1105">
		<idioma identificador="1">
			<texto>Ejecución paso a paso</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Step by step</texto>
		</idioma>
	</entrada>
	<entrada numero="1106">
		<idioma identificador="1">
			<texto>Estructura de datos estudiada en Estructura de Datos(2ºI.T.I.S.)</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Data Structure studied in Data Structure(2ºI.T.I.S.)</texto>
		</idioma>
	</entrada>
	<entrada numero="1107">
		<idioma identificador="1">
			<texto>Pre-orden</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Pre-order</texto>
		</idioma>
	</entrada>
	<entrada numero="1108">
		<idioma identificador="1">
			<texto>En-orden</texto>
		</idioma>
		<idioma identificador="2">
			<texto>In-order</texto>
		</idioma>
	</entrada>
	<entrada numero="111">
		<idioma identificador="1">
			<texto>Post-orden</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Post-order</texto>
		</idioma>
	</entrada>
	<entrada numero="1110">
		<idioma identificador="1">
			<texto>Por niveles</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Level-order</texto>
		</idioma>
	</entrada>
	<entrada numero="1111">
		<idioma identificador="1">
			<texto>¿Qué recorrido desea realizar?</texto>
		</idioma>
		<idioma identificador="2">
			<texto>What route do you want to do?</texto>
		</idioma>
	</entrada>
	<entrada numero="1113">
		<idioma identificador="1">
			<texto>Selección de recorrido</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Route selection</texto>
		</idioma>
	</entrada>
	<entrada numero="1114">
		<idioma identificador="1">
			<texto>Paso a paso</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Step by step</texto>
		</idioma>
	</entrada>
		<entrada numero="1115">
		<idioma identificador="1">
			<texto>¿Qué modo desea usar?</texto>
		</idioma>
		<idioma identificador="2">
			<texto>What mode do you want to use?</texto>
		</idioma>
	</entrada>
	<entrada numero="1116">
		<idioma identificador="1">
			<texto>Selección de modo</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Select a mode</texto>
		</idioma>
	</entrada>
	<entrada numero="1117">
		<idioma identificador="1">
			<texto>Hijo izquierdo</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Left node</texto>
		</idioma>
	</entrada>
	<entrada numero="1118">
		<idioma identificador="1">
			<texto>Hijo derecho</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Right node</texto>
		</idioma>
	</entrada>
	<entrada numero="1119">
		<idioma identificador="1">
			<texto>¿Qué inserción desea realizar?</texto>
		</idioma>
		<idioma identificador="2">
			<texto>What insertion do you want to do?</texto>
		</idioma>
	</entrada>
	<entrada numero="1120">
		<idioma identificador="1">
			<texto>Selección de inserción</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Select an insertion</texto>
		</idioma>
	</entrada>
	<entrada numero="1121">
		<idioma identificador="1">
			<texto>Introduzca valor para la raíz (núm.entero)</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Introduce a value for root (integer number)</texto>
		</idioma>
	</entrada>
	<entrada numero="1123">
		<idioma identificador="1">
			<texto>Aviso. No ha introducido nada</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Warning. You have introduced nothing</texto>
		</idioma>
	</entrada>
	<entrada numero="1124">
		<idioma identificador="1">
			<texto>Insertado(raíz): </texto>
		</idioma>
		<idioma identificador="2">
			<texto>Inserted(root): </texto>
		</idioma>
	</entrada>
	<entrada numero="1125">
		<idioma identificador="1">
			<texto>Aviso. Debe introducir un entero(-1000,1000)</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Warning. You must introduce an integer(-1000,1000)</texto>
		</idioma>
	</entrada>
	<entrada numero="1126">
		<idioma identificador="1">
			<texto>Operación es vacío</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Method es vacío</texto>
		</idioma>
	</entrada>
	<entrada numero="1127">
		<idioma identificador="1">
			<texto>El arbol está vacío</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Empty tree</texto>
		</idioma>
	</entrada>
	<entrada numero="1128">
		<idioma identificador="1">
			<texto>El árbol no esta vacío</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Not empty tree</texto>
		</idioma>
	</entrada>
	<entrada numero="1129">
		<idioma identificador="1">
			<texto>Vaciado de árbol binario</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Make empty binary tree</texto>
		</idioma>
	</entrada>
	<entrada numero="1130">
		<idioma identificador="1">
			<texto>Se ha vaciado el árbol</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Binary tree has been made empty</texto>
		</idioma>
	</entrada>
	<entrada numero="1131">
		<idioma identificador="1">
			<texto>Imposible vaciar árbol: árbol ya vacío</texto>
		</idioma>
		<idioma identificador="2">
			<texto>It's impossible to make empty tree: binary tree is empty yet!</texto>
		</idioma>
	</entrada>
	<entrada numero="1132">
		<idioma identificador="1">
			<texto>Operación tamaño</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Method size</texto>
		</idioma>
	</entrada>
		<entrada numero="1133">
		<idioma identificador="1">
			<texto>Tamaño del árbol: </texto>
		</idioma>
		<idioma identificador="2">
			<texto>Tree size: </texto>
		</idioma>
	</entrada>
	<entrada numero="1134">
		<idioma identificador="1">
			<texto>Operación altura</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Operación height</texto>
		</idioma>
	</entrada>
	<entrada numero="1135">
		<idioma identificador="1">
			<texto>Altura del árbol: </texto>
		</idioma>
		<idioma identificador="2">
			<texto>Tree height: </texto>
		</idioma>
	</entrada>
	<entrada numero="1136">
		<idioma identificador="1">
			<texto>Introduzca valor del nodo padre</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Introduce father node value</texto>
		</idioma>
	</entrada>
	<entrada numero="1137">
		<idioma identificador="1">
			<texto>Aviso: no se pueden introducir valores repetidos</texto>
		</idioma>
		<idioma identificador="2">
			<texto>It is not possible to be introduced repeated values </texto>
		</idioma>
	</entrada>
	<entrada numero="1138">
		<idioma identificador="1">
			<texto>Insertado(hijo izquierdo): </texto>
		</idioma>
		<idioma identificador="2">
			<texto>Inserted (left child): </texto>
		</idioma>
	</entrada>
	<entrada numero="1139">
		<idioma identificador="1">
			<texto>Aviso: debe introducir un entero (-1000,1000) que exista en el árbol</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Warning: you must introduce an integer (-1000,1000) existing in the tree</texto>
		</idioma>
	</entrada>
	<entrada numero="1140">
		<idioma identificador="1">
			<texto>Insertado(hijo derecho): </texto>
		</idioma>
		<idioma identificador="2">
			<texto>Inserted (right child): </texto>
		</idioma>
	</entrada>
	<entrada numero="1141">
		<idioma identificador="1">
			<texto>Introducir valor del nodo hijo</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Introduce child node value</texto>
		</idioma>
	</entrada>
	<entrada numero="1142">
		<idioma identificador="1">
			<texto>Si</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Yes</texto>
		</idioma>
	</entrada>
		<entrada numero="1143">
		<idioma identificador="1">
			<texto>Información TDA Árbol binario búsqueda</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Information TDA Binary Search Tree</texto>
		</idioma>
	</entrada>
	<entrada numero="1144">
		<idioma identificador="1">
			<texto>TDA A.B.B.</texto>
		</idioma>
		<idioma identificador="2">
			<texto>TDA B.S.T.</texto>
		</idioma>
	</entrada>
	<entrada numero="1145">
		<idioma identificador="1">
			<texto>Insertar</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Insert</texto>
		</idioma>
	</entrada>
	<entrada numero="1146">
		<idioma identificador="1">
			<texto>Inserta un elemento</texto>
		</idioma>
		<idioma identificador="2">
			<texto> Insert into the tree; duplicates are ignored</texto>
		</idioma>
	</entrada>
	<entrada numero="1147">
		<idioma identificador="1">
			<texto>Eliminar</texto>
		</idioma>
		<idioma identificador="2">
			<texto>Remove</texto>
		</idioma>
	</entrada>
	<entrada numero="1148">
		<idioma identificador="1">
			<texto>Elimina un elemento</texto>
		</idioma>