
<!DOCTYPE SIMULACION
[
<!ELEMENT SIMULACION (OPCIONES,(COMPONENTES,CONEXIONES*)+) >
<!ELEMENT OPCIONES (ALTOP,ANCHOP,TIEMPO,PERIODOMUESTREO)>
<!ELEMENT COMPONENTES (PULSO|SINUSOIDAL|FILTRO|SUMADOR|MULTIPLICADOR|OSCILOSCOPIO|DIFUSOR|COMUNICACIONESENTRADA|COMUNICACIONESSALIDA|CUANTIZADOR|MUESTREADOR|GENERADORFICHERO|CODIFICADOR|SALIDAFICHERO|DECODIFICADOR)+ >
<!ELEMENT CONEXIONES (NUM_COMP_EMISOR,(NUM_CONECTOR,NUM_COMP_RECEPTOR)+) >
<!ELEMENT CONEXIONESREMOTAS (NUMEROLOCAL,ORDENADORREMOTO,NUMEROREMOTO) >
<!ELEMENT DATOS_COMPONENTE (POSICIONX,POSICIONY,DESCRIPCION,INFORME)>
<!ELEMENT PULSO (DATOS_COMPONENTE,TIPO,PERIODICO,AMPLITUD,ANCHO,PERIODO,MUESTREO,TIPO_SENAL)>
<!ELEMENT SINUSOIDAL (DATOS_COMPONENTE,AMPLITUD,FRECUENCIA,FASE,MUESTREO)>
<!ELEMENT FILTRO (DATOS_COMPONENTE,TIPOFILTRO,FRECUENCIA_C,FRECUENCIA_I,FRECUENCIA_D)>
<!ELEMENT SUMADOR (DATOS_COMPONENTE)>
<!ELEMENT OSCILOSCOPIO (DATOS_COMPONENTE)>
<!ELEMENT MULTIPLICADOR (DATOS_COMPONENTE)>
<!ELEMENT DIFUSOR (DATOS_COMPONENTE)>
<!ELEMENT COMUNICACIONESENTRADA (DATOS_COMPONENTE,NUMEROLOCAL,CONEXIONESREMOTAS*)>
<!ELEMENT COMUNICACIONESSALIDA (DATOS_COMPONENTE,NUMEROLOCAL,CONEXIONESREMOTAS*)>
<!ELEMENT CUANTIZADOR (DATOS_COMPONENTE,NIVELES,LIMITEMIN,LIMITEMAX,MUESTREOPERIODO,TIEMPOMUESTRA)>
<!ELEMENT MUESTREADOR (DATOS_COMPONENTE,MUESTREOPERIODO,TIEMPOMUESTRA)>
<!ELEMENT GENERADORFICHERO (DATOS_COMPONENTE,FICHERO)>
<!ELEMENT SALIDAFICHERO (DATOS_COMPONENTE,FICHERO)>
<!ELEMENT CODIFICADOR (DATOS_COMPONENTE,TIPOCODIFICADOR,NIVELES,LIMITEMIN,LIMITEMAX,MUESTREOPERIODO,TIEMPOMUESTRA)>
<!ELEMENT DECODIFICADOR (DATOS_COMPONENTE,TIPOCODIFICADOR,NIVELES,LIMITEMIN,LIMITEMAX,MUESTREOPERIODO,TIEMPOMUESTRA)>
<!ELEMENT ALTOP (#PCDATA)>
<!ELEMENT ANCHOP (#PCDATA)>
<!ELEMENT TIEMPO (#PCDATA)>
<!ELEMENT PERIODOMUESTREO (#PCDATA)>
<!ELEMENT NUM_COMP_EMISOR (#PCDATA)>
<!ELEMENT NUM_COMP_RECEPTOR (#PCDATA)>
<!ELEMENT NUM_CONECTOR (#PCDATA)>
<!ELEMENT POSICIONX (#PCDATA)>
<!ELEMENT POSICIONY (#PCDATA)>
<!ELEMENT DESCRIPCION (#PCDATA)>
<!ELEMENT INFORME (#PCDATA)>
<!ELEMENT TIPO (#PCDATA)>
<!ELEMENT TIPOFILTRO (#PCDATA)>
<!ELEMENT PERIODICO (#PCDATA)>
<!ELEMENT AMPLITUD (#PCDATA)>
<!ELEMENT ANCHO (#PCDATA)>
<!ELEMENT PERIODO (#PCDATA)>
<!ELEMENT MUESTREO (#PCDATA)>
<!ELEMENT TIPO_SENAL (#PCDATA)>
<!ELEMENT FRECUENCIA (#PCDATA)>
<!ELEMENT FASE (#PCDATA)>
<!ELEMENT FRECUENCIA_C (#PCDATA)>
<!ELEMENT FRECUENCIA_I (#PCDATA)>
<!ELEMENT FRECUENCIA_D (#PCDATA)>
<!ELEMENT NUMEROLOCAL (#PCDATA)>
<!ELEMENT ORDENADORREMOTO (#PCDATA)>
<!ELEMENT NUMEROREMOTO (#PCDATA)>
<!ELEMENT NIVELES (#PCDATA)>
<!ELEMENT LIMITEMIN (#PCDATA)>
<!ELEMENT LIMITEMAX (#PCDATA)>
<!ELEMENT MUESTREOPERIODO (#PCDATA)>
<!ELEMENT TIEMPOMUESTRA (#PCDATA)>
<!ELEMENT TIPOCODIFICADOR (#PCDATA)>
<!ELEMENT FICHERO (#PCDATA)>
<!ATTLIST ALTOP altop NMTOKEN #IMPLIED>
<!ATTLIST ANCHOP anchop NMTOKEN #IMPLIED>
<!ATTLIST TIEMPO tiempo NMTOKEN #IMPLIED>
<!ATTLIST PERIODOMUESTREO periodomuestreo NMTOKEN #IMPLIED>
<!ATTLIST NUM_COMP_EMISOR comp_emisor NMTOKEN #IMPLIED>
<!ATTLIST NUM_COMP_RECEPTOR comp_receptor NMTOKEN #IMPLIED>
<!ATTLIST NUM_CONECTOR	num_conector NMTOKEN #IMPLIED>
<!ATTLIST POSICIONX posx NMTOKEN #IMPLIED>
<!ATTLIST POSICIONY posy NMTOKEN #IMPLIED>
<!ATTLIST DESCRIPCION descripcion CDATA #IMPLIED>
<!ATTLIST INFORME informe CDATA #IMPLIED>
<!ATTLIST TIPO tipo NMTOKEN #IMPLIED>
<!ATTLIST TIPOFILTRO tipofiltro NMTOKEN #IMPLIED>
<!ATTLIST PERIODICO periodico NMTOKEN #IMPLIED>
<!ATTLIST AMPLITUD amplitud NMTOKEN #IMPLIED>
<!ATTLIST ANCHO ancho NMTOKEN #IMPLIED>
<!ATTLIST PERIODO periodo NMTOKEN #IMPLIED>
<!ATTLIST MUESTREO muestreo NMTOKEN #IMPLIED>
<!ATTLIST TIPO_SENAL tipo_senal NMTOKEN #IMPLIED>
<!ATTLIST FRECUENCIA frecuencia NMTOKEN #IMPLIED>
<!ATTLIST FASE fase NMTOKEN #IMPLIED>
<!ATTLIST FRECUENCIA_C frecuencia_c NMTOKEN #IMPLIED>
<!ATTLIST FRECUENCIA_I frecuencia_i NMTOKEN #IMPLIED>
<!ATTLIST FRECUENCIA_D frecuencia_d NMTOKEN #IMPLIED>
<!ATTLIST NUMEROLOCAL numerolocal NMTOKEN #IMPLIED>
<!ATTLIST ORDENADORREMOTO ordenadorremoto NMTOKEN #IMPLIED>
<!ATTLIST NUMEROREMOTO numeroremoto NMTOKEN #IMPLIED>
<!ATTLIST NIVELES niveles NMTOKEN #IMPLIED>
<!ATTLIST LIMITEMIN limitemin NMTOKEN #IMPLIED>
<!ATTLIST LIMITEMAX limitemax NMTOKEN #IMPLIED>
<!ATTLIST TIEMPOMUESTRA tiempomuestra NMTOKEN #IMPLIED>
<!ATTLIST MUESTREOPERIODO muestreoperiodo NMTOKEN #IMPLIED>
<!ATTLIST TIPOCODIFICADOR tipocodificador NMTOKEN #IMPLIED>
<!ATTLIST FICHERO fichero CDATA #IMPLIED>
]
>

<SIMULACION>
<OPCIONES>
<ALTOP altop='1000'></ALTOP>
<ANCHOP anchop='1000'></ANCHOP>
<TIEMPO tiempo='61.425'></TIEMPO>
<PERIODOMUESTREO periodomuestreo='0.015'></PERIODOMUESTREO>
</OPCIONES>
<COMPONENTES>
<GENERADORFICHERO>
<DATOS_COMPONENTE>
<POSICIONX posx='595'></POSICIONX>
<POSICIONY posy='259'></POSICIONY>
<DESCRIPCION descripcion=''></DESCRIPCION>
<INFORME informe='true'></INFORME>
</DATOS_COMPONENTE>
<FICHERO fichero='C:\Users\daniel\Desktop\Sesión 5 SyS\jpscdia2b.txt'></FICHERO>
</GENERADORFICHERO>
</COMPONENTES>
<CONEXIONES>
<NUM_COMP_EMISOR comp_emisor='0'></NUM_COMP_EMISOR>
<NUM_CONECTOR num_conector='0'></NUM_CONECTOR>
<NUM_COMP_RECEPTOR comp_receptor='1'></NUM_COMP_RECEPTOR>
</CONEXIONES>
<COMPONENTES>
<MUESTREADOR>
<DATOS_COMPONENTE>
<POSICIONX posx='515'></POSICIONX>
<POSICIONY posy='259'></POSICIONY>
<DESCRIPCION descripcion=''></DESCRIPCION>
<INFORME informe='true'></INFORME>
</DATOS_COMPONENTE>
<MUESTREOPERIODO muestreoperiodo='0.15'></MUESTREOPERIODO>
<TIEMPOMUESTRA tiempomuestra='0.1'></TIEMPOMUESTRA>
</MUESTREADOR>
</COMPONENTES>
<CONEXIONES>
<NUM_COMP_EMISOR comp_emisor='1'></NUM_COMP_EMISOR>
<NUM_CONECTOR num_conector='0'></NUM_CONECTOR>
<NUM_COMP_RECEPTOR comp_receptor='2'></NUM_COMP_RECEPTOR>
</CONEXIONES>
<COMPONENTES>
<CODIFICADOR>
<DATOS_COMPONENTE>
<POSICIONX posx='435'></POSICIONX>
<POSICIONY posy='259'></POSICIONY>
<DESCRIPCION descripcion=''></DESCRIPCION>
<INFORME informe='true'></INFORME>
</DATOS_COMPONENTE>
<TIPOCODIFICADOR tipocodificador='2'></TIPOCODIFICADOR>
<NIVELES niveles='4'></NIVELES>
<LIMITEMIN limitemin='-42.0'></LIMITEMIN>
<LIMITEMAX limitemax='42.0'></LIMITEMAX>
<MUESTREOPERIODO muestreoperiodo='0.15'></MUESTREOPERIODO>
<TIEMPOMUESTRA tiempomuestra='0.1'></TIEMPOMUESTRA>
</CODIFICADOR>
</COMPONENTES>
<CONEXIONES>
<NUM_COMP_EMISOR comp_emisor='2'></NUM_COMP_EMISOR>
<NUM_CONECTOR num_conector='0'></NUM_CONECTOR>
<NUM_COMP_RECEPTOR comp_receptor='3'></NUM_COMP_RECEPTOR>
</CONEXIONES>
<COMPONENTES>
<DECODIFICADOR>
<DATOS_COMPONENTE>
<POSICIONX posx='355'></POSICIONX>
<POSICIONY posy='259'></POSICIONY>
<DESCRIPCION descripcion=''></DESCRIPCION>
<INFORME informe='true'></INFORME>
</DATOS_COMPONENTE>
<TIPOCODIFICADOR tipocodificador='2'></TIPOCODIFICADOR>
<NIVELES niveles='4'></NIVELES>
<LIMITEMIN limitemin='-42.0'></LIMITEMIN>
<LIMITEMAX limitemax='42.0'></LIMITEMAX>
<MUESTREOPERIODO muestreoperiodo='0.15'></MUESTREOPERIODO>
<TIEMPOMUESTRA tiempomuestra='0.1'></TIEMPOMUESTRA>
</DECODIFICADOR>
</COMPONENTES>
<CONEXIONES>
<NUM_COMP_EMISOR comp_emisor='3'></NUM_COMP_EMISOR>
<NUM_CONECTOR num_conector='0'></NUM_CONECTOR>
<NUM_COMP_RECEPTOR comp_receptor='4'></NUM_COMP_RECEPTOR>
</CONEXIONES>
<COMPONENTES>
<FILTRO>
<DATOS_COMPONENTE>
<POSICIONX posx='275'></POSICIONX>
<POSICIONY posy='259'></POSICIONY>
<DESCRIPCION descripcion=''></DESCRIPCION>
<INFORME informe='true'></INFORME>
</DATOS_COMPONENTE>
<TIPOFILTRO tipofiltro='0'></TIPOFILTRO>
<FRECUENCIA_C frecuencia_c='2500.0'></FRECUENCIA_C>
<FRECUENCIA_I frecuencia_i='0.0'></FRECUENCIA_I>
<FRECUENCIA_D frecuencia_d='0.0'></FRECUENCIA_D>
</FILTRO>
</COMPONENTES>
<CONEXIONES>
<NUM_COMP_EMISOR comp_emisor='4'></NUM_COMP_EMISOR>
<NUM_CONECTOR num_conector='0'></NUM_CONECTOR>
<NUM_COMP_RECEPTOR comp_receptor='6'></NUM_COMP_RECEPTOR>
</CONEXIONES>
<COMPONENTES>
<OSCILOSCOPIO>
<DATOS_COMPONENTE>
<POSICIONX posx='67'></POSICIONX>
<POSICIONY posy='307'></POSICIONY>
<DESCRIPCION descripcion=''></DESCRIPCION>
<INFORME informe='true'></INFORME>
</DATOS_COMPONENTE>
</OSCILOSCOPIO>
</COMPONENTES>
<COMPONENTES>
<DIFUSOR>
<DATOS_COMPONENTE>
<POSICIONX posx='163'></POSICIONX>
<POSICIONY posy='259'></POSICIONY>
<DESCRIPCION descripcion=''></DESCRIPCION>
<INFORME informe='true'></INFORME>
</DATOS_COMPONENTE>
</DIFUSOR>
</COMPONENTES>
<CONEXIONES>
<NUM_COMP_EMISOR comp_emisor='6'></NUM_COMP_EMISOR>
<NUM_CONECTOR num_conector='0'></NUM_CONECTOR>
<NUM_COMP_RECEPTOR comp_receptor='5'></NUM_COMP_RECEPTOR>
</CONEXIONES>
<CONEXIONES>
<NUM_COMP_EMISOR comp_emisor='6'></NUM_COMP_EMISOR>
<NUM_CONECTOR num_conector='1'></NUM_CONECTOR>
<NUM_COMP_RECEPTOR comp_receptor='7'></NUM_COMP_RECEPTOR>
</CONEXIONES>
<COMPONENTES>
<SALIDAFICHERO>
<DATOS_COMPONENTE>
<POSICIONX posx='67'></POSICIONX>
<POSICIONY posy='211'></POSICIONY>
<DESCRIPCION descripcion=''></DESCRIPCION>
<INFORME informe='true'></INFORME>
</DATOS_COMPONENTE>
<FICHERO fichero='C:\Users\daniel\Desktop\Sesión 5 SyS\simulacion.xml'></FICHERO>
</SALIDAFICHERO>
</COMPONENTES>
</SIMULACION>
